version: '3'
services:
  web:
    image: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
  db:
    image: postgres
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./projetoFinal:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
