# Generated by Django 2.1.7 on 2019-03-10 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0003_parameter_rotary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.DateTimeField(auto_now_add=True, verbose_name='Entrada')),
                ('output', models.DateTimeField(blank=True, null=True, verbose_name='Saída')),
                ('paid', models.BooleanField(default=False, verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Mensalista',
            },
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Marca'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': 'Parâmetros'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Pessoa'},
        ),
        migrations.AlterModelOptions(
            name='rotary',
            options={'verbose_name': 'Rotativo'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Veículo'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='people',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='people',
            name='telephone',
            field=models.CharField(max_length=14, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='rotary',
            name='input',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='rotary',
            name='output',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Saída'),
        ),
        migrations.AlterField(
            model_name='rotary',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='rotary',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamento.Vehicle', verbose_name='Veículo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='board',
            field=models.CharField(max_length=7, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estacionamento.Brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(max_length=10, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='note',
            field=models.TextField(verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estacionamento.People', verbose_name='Proprietário(a)'),
        ),
        migrations.AddField(
            model_name='monthly',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamento.Vehicle', verbose_name='Veículo'),
        ),
    ]
