# Generated by Django 2.1.7 on 2019-03-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0004_auto_20190310_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly',
            name='input',
            field=models.DateTimeField(verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='rotary',
            name='input',
            field=models.DateTimeField(verbose_name='Entrada'),
        ),
    ]
